repo: "masthead-semantics"
canvasCourse: "467502"
canvasAssignment: "4178288"

naming: true
commits: 3

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ""
    search:
      - ""
