repo: "masthead-semantics"
canvasCourse: "web-dev-1"

inherit:
  - naming-restrict-live
  - git-2
  - html

html:
  - path: "index.html"
    has:
      - "header"
      - "header img"
      - "header h1"
      - "header nav"
      - "header nav ul"
      - "header nav ul li"
      - "header nav ul li a"
      - "figure"
      - "figure img"
      - "figure figcaption"
      - "main"
      - "main p"
    search:
      - "The Solar System"
      - "Stars"
      - "Terrestrial planets"
      - "Gas giants"
      - "Dwarf planets"
      - "Asteroids"
      - "Comets"
      - "gravitationally"
